### PR TITLE
Phase 6 Tasks | SkyNet

### PR DESCRIPTION
**Pull request by lightiv**
This should complete all Phase 6 tasks.  Let me know if anything is missing.  Paul | SkyNet

### CODE REVIEW

**Review by RiccardoM — CHANGES_REQUESTED** [review]
Hey @lightiv, thanks for the submission! If you want I'm going to merge this since it seems all right. 

However, please note that there is one more challenge that you can complete: [Change your DTag](https://primer.desmos.network/phase-6/change-dtag.html)!

Also, before merging can you please change all the file names to `lightiv` please? Thank you!

**Comment by lightiv** [comment]
Hi Riccardo, how do I rename them at this point?

**Comment by RiccardoM** [comment]
> Hi Riccardo, how do I rename them at this point?

You can use this line

```
for filename in $(find -regex '*SkyNet*'); do echo mv \"$filename\" \"${filename//SkyNet/lightiv}\"; done | /bin/bash
```

Then, once changed, commit and push: 

```
git add .
git commit -m "Renamed files"
git push
```

**Comment by lightiv** [comment]
Unfortunately  the above command doesn't change any file names.  Can I just manually change them?

**Comment by lightiv** [comment]
I found where to rename the files here on gitHub and commit them.  Hopefully this is what is needed.  Please let me know.

**Comment by RiccardoM** [comment]
> I found where to rename the files here on gitHub and commit them. Hopefully this is what is needed. Please let me know.

Perfect!

**Review by RiccardoM — APPROVED** [review]

**Pull request merged**
