### PR TITLE
Phase 3 

### PR DESCRIPTION
**Pull request by rkyassine**

### CODE REVIEW

**Comment by RiccardoM** [comment]
Hi @rkyassine, thanks for the submission! :pray: As we've moved Phase 1 & 2 files, would you mind deleting them as well from your files and committing the changes? Thanks so much!

**Comment by rkyassine** [comment]
> 
> 
> Hi @rkyassine, thanks for the submission! 🙏 As we've moved Phase 1 & 2 files, would you mind deleting them as well from your files and committing the changes? Thanks so much!

hello, is it ok now ?

**Comment by RiccardoM** [comment]
> hello, is it ok now ?
Hi @rkyassine. No, it is not OK sorry. 

You have deleted the files that were there instead of the ones you have added. 

To create a proper PR, please reference [your changed files](https://github.com/desmos-labs/primer/pull/166/files), the ones from an [already accepted PR](https://github.com/desmos-labs/primer/pull/168/files) and make sure they are the same number and type. 

You need to: 

1. Bring back `phase-1/submissions/likes/rkyassine`
2. Bring back `phase-1/submissions/referral/rkyassine`
3. Delete `phases/phase-1/challenges/posts/rkyassine`
4. Delete `phases/phase-2/challenges/reactions/rkyassine`
5. Delete `phases/phase-2/challenges/validators/rkyassine`

Once you have done so, please commit the changes and push them. Thanks.

**Comment by rkyassine** [comment]
Hi, i have deleted the files you asked me about. did i miss something ?

**Comment by RiccardoM** [comment]
Hi @rkyassine, you need to bring back the following files:

```
phase-1/submissions/posts/rkyassine
phase-2/submissions/reactions/rkyassine
phase-2/submissions/validators/rkyassine
```

**Comment by rkyassine** [comment]
hello, sorry for late response. I have added back the files you asked for.

**Pull request merged**
